### ISSUE TITLE
any thought to adding support for Xamarin Forms?

### ISSUE THREAD

**Issue by ravensorb** [HoussemDellai/CrossVideoPlayer#1]
Would love to be able to use this in a PCL Xamarin Forms project.  Any thoughts on adding support?

**Comment by HoussemDellai** [comment]
It already works with PCL!

**Comment by ravensorb** [comment]
Not exactly.  The current nugget package will not install in a PCL project.  I updated the nuspec file and now it will install in Profile111.

I am also in the process of updating it to Xamarin 2.1 and adding support for iOS and Windows Universal.  I'll do a PR when it is ready.

**Comment by wiltwitt** [comment]
That will be awesome ravensorb.  I need to implement video player that will also work for ios with forms.  Thanks!
